name: postwit.docker-compose
services:
  postwit.api:
    image: ${DOCKER_REGISTRY-}postwitapi
    build:
      context: .
      dockerfile: src/Postwit.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    environment:
      # Aspire Dashboard
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://postwit.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
  
  postwit.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888

  postwit.postgres:
    image: postgres:17.2
    environment:
      POSTGRES_DB: postwit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432